### ISSUE TITLE
createAzureFunctionsMiddleware mentioned in README.md does not exist in code

### ISSUE THREAD

**Issue by h-no** [probot/adapter-azure-functions#3]
Hi, I believe there is a mismatch with the code and the README.md. (JavaScript is not my first language, however :) )
I am not sure which you prefer, but following the README I had to replace `createAzureFunctionsMiddleware` with `createAzureFunction`.

**Comment by gr2m** [comment]
You are correct, the README needs to be updated, `createAzureFunctionsMiddleware` is wrong, the correct function name is `createAzureFunction`. Thank you!

Would you like to send a pull request yourself?

**Comment by gr2m** [comment]
You are correct, the README needs to be updated, `createAzureFunctionsMiddleware` is wrong, the correct function name is `createAzureFunction`. Thank you!

Would you like to send a pull request yourself?

**Comment by h-no** [comment]
> You are correct, the README needs to be updated, `createAzureFunctionsMiddleware` is wrong, the correct function name is `createAzureFunction`. Thank you!
> 
> Would you like to send a pull request yourself?

Sure, I posted a PR!
