### ISSUE TITLE
Typescript compilation error

### ISSUE THREAD

**Issue by akbast** [probot/adapter-azure-functions#56]
Hey,

I am using adapter azure functions within typescript. When I import `Probot` in oder to use typings, I get following errors:

```
node_modules/@octokit/webhooks/dist-types/types.d.ts:6:163 - error TS1005: ';' expected.

6 export declare type EmitterWebhookEvent<TEmitterEvent extends EmitterWebhookEventName = EmitterWebhookEventName> = TEmitterEvent extends `${infer TWebhookEvent}.${infer TAction}` ? BaseWebhookEvent<Extract<TWebhookEvent, WebhookEventName>> & {~
```

My app.ts looks like following:

```
import { Probot } from "probot";

export const probotApp = (app: Probot) => {
  app.on("push", async (context) => {
    console.info("got push")
  })
};
```

I am using the latest version of the package. 

Any Idea what am I missing? Would appreciate if you could provide an example based on Typescript like [this one](https://github.com/probot/example-azure-function/).

Thanks

**Comment by gr2m** [comment]
What TypeScript version are you using? What `@octokit/webhooks` version do you have installed?

**Comment by akbast** [comment]
Typescript version is 3.9.10. `@octokit/webhooks` is as following:

```
└─┬ @probot/adapter-azure-functions@1.0.13
  └─┬ probot@12.1.1
    └── @octokit/webhooks@9.17.0
```

**Comment by gr2m** [comment]
It's most likely due to the outdated TypeScript version. We only support the latest.

I think 3.x does not support template literals.

Please upgrade to latest TypeScript. Let us know if that resolved the problem

**Comment by akbast** [comment]
Updating typescript to the latest version did the trick. Thanks
